server:
  port: 85
  servlet:
    context-path: /bpm
    session:
      timeout: 480m

logging:
  file:
    path: d:/logs/bpm
    name: d:/logs/bpm/bpm.log
  level:
    root: INFO
    com:
      walsin: TRACE
    
bpm:
  datasource:    
    unique-resource-name: bpmDataSource
    pool-size: 3
    max-pool-size: 5
    min-pool-size: 2
    max-life-time: 120
    max-idle-time: 60
    borrow-connection-timeout: 60
    # xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
    xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
    xa-properties:
      user: sa
      password: password
      URL: jdbc:h2:file:d:\\h2\\home\\flowable;DB_CLOSE_ON_EXIT=FALSE
      # user: flowable
      # password: flowable@23
      # URL: jdbc:mysql://34.80.82.226:3306/flowable?useSSL=false
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
    format_sql: true
    show_sql: true
### 人員資料庫連線設定 ###
app:
  datasource:
    unique-resource-name: appDataSource
    pool-size: 3
    max-pool-size: 5
    min-pool-size: 2
    max-life-time: 120
    max-idle-time: 60
    borrow-connection-timeout: 60
    xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
    xa-properties:
      user: sa
      password: password
      URL: jdbc:h2:file:d:\\h2\\home\\app;DB_CLOSE_ON_EXIT=FALSE

### Hibernate 屬性設定 ###
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
    format_sql: true
    show_sql: true
    
spring:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  datasource:
    schema:
    - classpath:sql/schema-test.sql
    data:
    # - classpath:sql/data.sql
    initialization-mode: ALWAYS
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
    - org.activiti.spring.boot.SecurityAutoConfiguration
    - org.flowable.spring.boot.idm.IdmEngineAutoConfiguration
    - org.flowable.spring.boot.idm.IdmEngineServicesAutoConfiguration